name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        assets:
          - unit-eval/build/libs/unit-eval-*-all.jar

    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'


      - name: Setup Gradle
        run: ./gradlew build --no-daemon  -x test

      - name: Upload assets to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.assets }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

